config/routes.rb
Byro::Application.routes.draw do
  devise_for :users
  resources :users

  resources :user_messages

  get '/sent_messages', to: 'user_messages#sent'

  resources :users
  
  root :to => 'user_messages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,  :handle
  # attr_accessible :title, :body

  has_many :user_messages, 
    :foreign_key => :to_user_id


  # scope :sent_messages, :conditions => { :highlight => true } #, :include => [:item]


end

app/models/user_message.rb
class UserMessage < ActiveRecord::Base
  attr_accessible :from_user_id, :to_user_id, :message, :subject, :to_user_id
  belongs_to :user

  validates :to_user_id, :numericality => { only_integer: true }
  validates :subject, :presence => {:message => 'Must have a subject'}
  validates :message, :presence => {:message => 'Must have a message'}


  scope :sent_messages, lambda { |current_user|
    where("user_messages.from_user_id = ?", current_user)
  } 

  scope :unread_messages, lambda { |current_user|
    #.reject{|r| r.read == true}.size.to_s
    where("user_messages.to_user_id = ? and user_messages.read = ?", current_user, false)
  } 


  def self.all_messages
    self.all
  end
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
end

app/controllers/user_messages_controller copy.rb
class UserMessagesController < ApplicationController
  # GET /user_messages
  # GET /user_messages.json
  def index
    # user = User.find(1)
    @user_messages = User.find(current_user).user_messages

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_messages }
    end
  end

  # GET /user_messages/1
  # GET /user_messages/1.json
  def show
    @user_message = UserMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_message }
    end
  end

  # GET /user_messages/new
  # GET /user_messages/new.json
  def new
    @user_message = UserMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_message }
    end
  end

  # GET /user_messages/1/edit
  def edit
    @user_message = UserMessage.find(params[:id])
  end

  # POST /user_messages
  # POST /user_messages.json
  def create
    @user_message = UserMessage.new(params[:user_message])

    respond_to do |format|
      if @user_message.save
        format.html { redirect_to @user_message, notice: 'User message was successfully created.' }
        format.json { render json: @user_message, status: :created, location: @user_message }
      else
        format.html { render action: "new" }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_messages/1
  # PUT /user_messages/1.json
  def update
    @user_message = UserMessage.find(params[:id])

    respond_to do |format|
      if @user_message.update_attributes(params[:user_message])
        format.html { redirect_to @user_message, notice: 'User message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_messages/1
  # DELETE /user_messages/1.json
  def destroy
    @user_message = UserMessage.find(params[:id])
    @user_message.destroy

    respond_to do |format|
      format.html { redirect_to user_messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_messages_controller.rb
class UserMessagesController < ApplicationController
  # GET /user_messages
  # GET /user_messages.json

  def sent
    @sent_messages = UserMessage.sent_messages(current_user.id)
  end


  def index
    # user = User.find(1)
    @user_messages = User.find(current_user.id).user_messages.order("read asc, created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_messages }
    end
  end

  # GET /user_messages/1
  # GET /user_messages/1.json
  def show
    @user_message = UserMessage.find(params[:id])

    # raise " #{@user_message.inspect}"

    if @user_message.read == false && @user_message.to_user_id == current_user.id
      @user_message.update_attribute(:read, true) 
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_message }
    end
  end

  # GET /user_messages/new
  # GET /user_messages/new.json
  def new
    @user_message = UserMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_message }
    end
  end

  # GET /user_messages/1/edit
  def edit
    @user_message = UserMessage.find(params[:id])
  end

  # POST /user_messages
  # POST /user_messages.json
  def create
    @user_message = UserMessage.new(params[:user_message])

    respond_to do |format|
      if @user_message.save
        format.html { redirect_to user_messages_path }
        format.json { render json: @user_message, status: :created, location: @user_message }
      else
        format.html { render action: "new" }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_messages/1
  # PUT /user_messages/1.json
  def update
    @user_message = UserMessage.find(params[:id])

    respond_to do |format|
      if @user_message.update_attributes(params[:user_message])
        format.html { redirect_to @user_message, notice: 'User message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_messages/1
  # DELETE /user_messages/1.json
  def destroy
    @user_message = UserMessage.find(params[:id])
    @user_message.destroy

    respond_to do |format|
      format.html { redirect_to user_messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def read_or_unread(status)
    status == false ? "Unread" : "Read"
  end

  def handle_lookup(id)
    User.find(id).handle
  end

  def unread_count(user_id)
    UserMessage.unread_messages(user_id).size
  end

end

app/helpers/user_messages_helper.rb
module UserMessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Byro</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "//cdn.jsdelivr.net/foundation/5.0.2/css/foundation.css" %>
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br> 
  <div class="row">
    <%= render "shared/nav" %>
    <%= yield %>
  </div>
</body>
</html>

app/views/sent_messages/index.slim
/ = raise "#{current_user.id}"

h1 Your sent Messages
table
  tr
    th To user
    th Subject
    th Message
    th
    th
    th
  - @sent_messages.each do |user_message|
    tr
      td= handle_lookup(user_message.to_user_id)
      td= user_message.subject
      td= user_message.message
      td= link_to 'Show', user_message
      td= link_to 'Edit', edit_user_message_path(user_message)
      / td= link_to 'Destroy', user_message, method: :delete, data:   confirm: 'Are you sure?' 
br/
= link_to 'New User message', new_user_message_path

app/views/shared/_nav.slim
- if user_signed_in?

  = link_to "your messages #{"<span class='number-circle'>"+ unread_count(current_user.id).to_s + '</span>' }".html_safe, user_messages_path, class: 'button'
  = link_to "new message", new_user_message_path, class: 'button'
  = link_to "sent messages", sent_messages_path, class: 'button'
  = link_to "users", users_path, class: 'button'
  = link_to "sign_out  #{current_user.handle}",  destroy_user_session_path, :method => :delete, class: 'button'

- else

  h1 you need to login to use this app.

app/views/user_messages/_form.html.erb
<%= form_for(@user_message) do |f| %>
  <% if @user_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_message.errors.count, "error") %> prohibited this user_message from being saved:</h2>

      <ul>
      <% @user_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.hidden_field :from_user_id, value: current_user.id  %>
  </div>


  
   <%= collection_select(:user_message, :to_user_id, User.all, :id, :handle, prompt: true)   %>


  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit :class => 'button'  %>
  </div>

<% end %>

app/views/user_messages/edit.html.erb
<h1>Editing user_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_message %> |
<%= link_to 'Back', user_messages_path %>

app/views/user_messages/index.html.erb
<h1>Your Mesages</h1>

<table>
  <tr>
    <th>From</th>
    <th>Subject</th>
    <th>Message</th>
    <th>READ</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_messages.each do |user_message| %>
  <tr>
    <td><%= handle_lookup(user_message.to_user_id) %></td>
    <td><%= user_message.subject %></td>
    <td><%= user_message.message %></td>
    <td><%= read_or_unread(user_message.read)   %></td>
    <td><%= link_to 'Show', user_message %></td>
    <td><%= link_to 'Edit', edit_user_message_path(user_message) %></td>
    <td><%= link_to 'Destroy', user_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User message', new_user_message_path, class: 'button' %>

app/views/user_messages/new.html.erb
<h1>Send a Message</h1>

<%= render 'form' %>

<%= link_to 'Back', user_messages_path %>

app/views/user_messages/sent.slim
/ = raise "#{current_user.id}"

h1 Your sent Messages
table
  tr
    th To user
    th Subject
    th Message
    th
    th
    th
  - @sent_messages.each do |user_message|
    tr
      //td= handle_lookup(user_message.to_user_id)
      td= user_message.subject
      td= user_message.message
      td= link_to 'Show', user_message
      td= link_to 'Edit', edit_user_message_path(user_message)
      / td= link_to 'Destroy', user_message, method: :delete, data:   confirm: 'Are you sure?' 
br/
= link_to 'New User message', new_user_message_path

app/views/user_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From user:</b>
  <%= @user_message.from_user_id %>
</p>

<p>
  <b>To user:</b>
  <%= @user_message.to_user_id %>
</p>

<p>
  <b>Subject:</b>
  <%= @user_message.subject %>
</p>

<p>
  <b>Message:</b>
  <%= @user_message.message %>
</p>



<%= link_to 'Edit', edit_user_message_path(@user_message) %> |
<%= link_to 'Back', user_messages_path %>

app/views/users/index.slim
.row
  h1 Users
  table
    tr
      th Handle
      th Email
      th Sent Messages
    - @users.each do |user|
      tr
        td = user.handle
        td = user.email
        td = UserMessage.find_all_by_from_user_id(user).size